In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_op = pd.read_csv('../../data/raw/ehn_gt_outpatient_20251223000.csv')

In [4]:
df_op.columns

Index(['eventdate', 'deid_personid', 'planpayer', 'patient_city',
       'patient_state', 'patient_zip', 'pcpnpi', 'pcpname', 'ehn_vs_non',
       'employed_vs_independent', 'ehn_practice', 'lhn', 'entity', 'cost',
       'paiddate', 'placeofservice', 'placeofservicedescription',
       'primary_cpt', 'cptdescription', 'primary_icd', 'icddescription',
       'servicing_prov', 'servicing_specialty', 'rptgrouper',
       'servicing_practice', 'servicing_lhn', 'servicing_entity'],
      dtype='object')

In [5]:
df_op.describe()

        patient_zip          cost  servicing_prov
count  5.825975e+06  5.825975e+06    4.666643e+06
mean   6.476963e+06  3.575200e+02    1.495963e+09
std    4.437435e+07  2.484616e+03    2.938401e+08
min    0.000000e+00 -4.134600e+04    7.956590e+05
25%    3.004700e+04  3.079000e+01    1.245273e+09
50%    3.013200e+04  9.819000e+01    1.487619e+09
75%    3.032700e+04  2.126300e+02    1.750757e+09
max    9.850288e+08  2.763458e+06    2.036789e+09

In [6]:
df_op.head()

,eventdate,deid_personid,planpayer,patient_city,patient_state,patient_zip,pcpnpi,pcpname,ehn_vs_non,employed_vs_independent,...,primary_cpt,cptdescription,primary_icd,icddescription,servicing_prov,servicing_specialty,rptgrouper,servicing_practice,servicing_lhn,servicing_entity
0,2024-01-01,0d37b3ac08dc91071b27d1d893198589,Emory Anthem Commercial,SHARPSBURG,GA,30277,1629307277,"LEWIS, BRIAN",EHN,EHN Employed,...,87426,IAAD IA SEVERE AQT RESPIR SYND CORONAVIRUS,J06.9,"Acute upper respiratory infection, unspecified",1.972779e+09,Emergency Medicine,LAB,Emory at Sharpsburg,SC,ESA
1,2024-01-01,0c8c2c1ae73541addaea18e9e729a4b7,Emory Humana MAdv,LOGANVILLE,GA,30052,1568576866,"DEIMLER, ROBERT",EHN,EHN Employed,...,NaN,NaN,N18.6,End stage renal disease,NaN,NaN,MEDICAL PHARMACY,Emory at Centerville,EDH,ESA
2,2024-01-01,3abc08ca4f28e8c6ee5ac81a17cdea18,Emory Aetna MAdv,STONE MOUNTAIN,GA,30087,1326027715,"KIM, SHAWN",EHN,EHN Independent,...,S9083,Global fee urgent care centers,R05.9,"Cough, unspecified",1.720487e+09,Clinic/Center,OTHER,GA Internal Medicine,EJCH,PRIVATE
3,2024-01-01,f6fc7f2fa57ce4ae5ba7c7a185e1ab8c,Emory Cigna Commercial,STONE MOUNTAIN,GA,30088,1902990336,"PATEL, DHARMESHKUMAR",EHN,EHN Independent,...,87661,IADNA TRICHOMONAS VAGINALIS AMPLIFIED PROBE TECH,A64,Unspecified sexually transmitted disease,1.932166e+09,Clinical Medical Laboratory,LAB,"Georgia Family Care, LLC",EDH,PRIVATE
4,2024-01-01,8c0945a484fafaf39bf33361ff55b0ba,Emory Anthem MAdv,COLUMBUS,GA,31904,1821483488,"ALLAWY, ALLAWY",EHN,EHN Independent,...,99458,REMOTE PHYSIOLOGIC MONITORING EA ADDL 20 MIN MO,I10,Essential (primary) hypertension,1.881776e+09,Family Medicine,PCP VISITS,Unknown,Unknown,Unknown

In [7]:
df_op.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5825975 entries, 0 to 5825974
Data columns (total 27 columns):
 #   Column                     Dtype
---  ------                     -----
 0   eventdate                  object
 1   deid_personid              object
 2   planpayer                  object
 3   patient_city               object
 4   patient_state              object
 5   patient_zip                int64
 6   pcpnpi                     object
 7   pcpname                    object
 8   ehn_vs_non                 object
 9   employed_vs_independent    object
 10  ehn_practice               object
 11  lhn                        object
 12  entity                     object
 13  cost                       float64
 14  paiddate                   object
 15  placeofservice             object
 16  placeofservicedescription  object
 17  primary_cpt                object
 18  cptdescription             object
 19  primary_icd                object
 20  icddescription             object
 21  servicing_prov             float64
 22  servicing_specialty        object
 23  rptgrouper                 object
 24  servicing_practice         object
 25  servicing_lhn              object
 26  servicing_entity           object
dtypes: float64(2), int64(1), object(24)
memory usage: 1.2+ GB

In [8]:
df_op[['ehn_practice', 'lhn', 'entity', 'cost', 'paiddate', 'placeofservice', 'placeofservicedescription']]

,ehn_practice,lhn,entity,cost,paiddate,placeofservice,placeofservicedescription
0,Emory at Sharpsburg,SC,ESA,184.77,2024-01-18,20,Urgent Care Facility
1,Emory at Centerville,EDH,ESA,0.00,2025-02-11,22,On Campus-Outpatient Hospital
2,GA Internal Medicine,EJCH,PRIVATE,210.00,2024-01-03,20,Urgent Care Facility
3,"Georgia Family Care, LLC",EDH,PRIVATE,1085.15,2024-01-08,81,Independent Laboratory
4,St. Francis Center for Digestive Disorders,SFH-EHC,PRIVATE,55.79,2024-01-26,11,Office
...,...,...,...,...,...,...,...
5825970,"Medical Associates of Georgia, Inc",EJCH,PRIVATE,112.07,2025-01-05,11,Office
5825971,"The Kaufmann Clinic, Inc",TERMED,PRIVATE,461.08,2025-01-16,11,Office
5825972,Unknown,Unknown,Unknown,3296.53,2025-01-16,22,On Campus-Outpatient Hospital
5825973,Emory at Downtown Decatur,EDH,ESA,158.90,2025-01-15,11,Office
5825974,Emory at Tucker - Montreal Road,EUH,ESA,36.66,2025-07-01,21,Inpatient Hospital

In [10]:
df_op.isnull().sum()

eventdate                          0
deid_personid                      0
planpayer                          0
patient_city                       0
patient_state                      4
patient_zip                        0
pcpnpi                             0
pcpname                            0
ehn_vs_non                         0
employed_vs_independent            0
ehn_practice                       0
lhn                            95286
entity                         57494
cost                               0
paiddate                       50736
placeofservice                 45917
placeofservicedescription      70781
primary_cpt                    94822
cptdescription                144484
primary_icd                   134411
icddescription                134563
servicing_prov               1159332
servicing_specialty           879933
rptgrouper                         0
servicing_practice             16366
servicing_lhn                 115375
servicing_entity               77498
dtype: int64

In [13]:
df_op.groupby('deid_personid').count()

,eventdate,planpayer,patient_city,patient_state,patient_zip,pcpnpi,pcpname,ehn_vs_non,employed_vs_independent,ehn_practice,...,primary_cpt,cptdescription,primary_icd,icddescription,servicing_prov,servicing_specialty,rptgrouper,servicing_practice,servicing_lhn,servicing_entity
deid_personid,,,,,,,,,,,,,,,,,,,,,
00005c8c0136e5d1e49f50700c83ccf7,7,7,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7
0000672cf36fc1586ff74101e9ee3d6e,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,7,20,20,20,20,20
00006961e0cd7e393b6075560382cfd4,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
0000e6a86c13982bddcaab914d3d127b,8,8,8,8,8,8,8,8,8,8,...,8,8,8,8,8,8,8,8,8,8
0000e96e2625f9ff3cff108d1a079afe,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ffff9e6383259898a8e75a2a12990c5d,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
ffffa8d43ecb5f4abb02fd6519ede0f1,52,52,52,52,52,52,52,52,52,52,...,47,47,52,52,23,36,52,52,52,52
ffffc5ced058b09c8876b694533c2131,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,3,10,10,10,10,10
ffffd7bf8c9e34de828bf4a16219a840,7,7,7,7,7,7,7,7,7,7,...,7,7,7,7,1,7,7,7,7,7
ffffda856e1b343b1c750fe858dcbc61,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14

In [17]:
df_op[df_op['deid_personid']=='0000672cf36fc1586ff74101e9ee3d6e']

,eventdate,deid_personid,planpayer,patient_city,patient_state,patient_zip,pcpnpi,pcpname,ehn_vs_non,employed_vs_independent,...,primary_cpt,cptdescription,primary_icd,icddescription,servicing_prov,servicing_specialty,rptgrouper,servicing_practice,servicing_lhn,servicing_entity
80800,2024-01-11,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,99214,OFFICE/OUTPATIENT ESTABLISHED MOD MDM 30 MIN,M47.814,Spondylosis without myelopathy or radiculopath...,NaN,No Specialty,SPECIALIST VISITS,"Southside Internal Medicine, PC",SC,PRIVATE
103927,2024-01-16,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,72100,RADEX SPINE LUMBOSACRAL 2/3 VIEWS,M54.59,Other low back pain,NaN,No Specialty,RADIOLOGY,"Southside Internal Medicine, PC",SC,PRIVATE
119903,2024-01-16,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,99204,OFFICE/OUTPATIENT NEW MODERATE MDM 45 MINUTES,M54.59,Other low back pain,NaN,No Specialty,SPECIALIST VISITS,"Southside Internal Medicine, PC",SC,PRIVATE
392757,2024-02-09,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,64479,NJX AA&/STRD TFRML EPI CERVICAL/THORACIC 1 LEVEL,M54.14,"Radiculopathy, thoracic region",NaN,No Specialty,OP PROCEDURES,"Southside Internal Medicine, PC",SC,PRIVATE
568768,2024-02-23,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,99214,OFFICE/OUTPATIENT ESTABLISHED MOD MDM 30 MIN,M54.14,"Radiculopathy, thoracic region",NaN,No Specialty,SPECIALIST VISITS,"Southside Internal Medicine, PC",SC,PRIVATE
777495,2024-03-12,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,64479,NJX AA&/STRD TFRML EPI CERVICAL/THORACIC 1 LEVEL,M54.14,"Radiculopathy, thoracic region",1.568860e+09,Physical Medicine & Rehabilitation,OP PROCEDURES,"Southside Internal Medicine, PC",SC,PRIVATE
2133914,2024-04-12,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,20610,ARTHROCENTESIS ASPIR&/INJ MAJOR JT/BURSA W/O US,M17.12,"Unilateral primary osteoarthritis, left knee",NaN,No Specialty,OTHER,"Southside Internal Medicine, PC",SC,PRIVATE
2218914,2024-07-09,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,99213,OFFICE/OUTPATIENT ESTABLISHED LOW MDM 20 MIN,M54.6,Pain in thoracic spine,NaN,No Specialty,SPECIALIST VISITS,"Southside Internal Medicine, PC",SC,PRIVATE
2229719,2024-04-05,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,99213,OFFICE/OUTPATIENT ESTABLISHED LOW MDM 20 MIN,M54.14,"Radiculopathy, thoracic region",NaN,No Specialty,SPECIALIST VISITS,"Southside Internal Medicine, PC",SC,PRIVATE
2616249,2024-08-15,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,45380,COLONOSCOPY W/BIOPSY SINGLE/MULTIPLE,Z12.11,Encounter for screening for malignant neoplasm...,NaN,No Specialty,OP PROCEDURES,"Southside Internal Medicine, PC",SC,PRIVATE
2820845,2024-04-29,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,99214,OFFICE/OUTPATIENT ESTABLISHED MOD MDM 30 MIN,N40.1,Benign prostatic hyperplasia with lower urinar...,NaN,No Specialty,SPECIALIST VISITS,"Southside Internal Medicine, PC",SC,PRIVATE
3478414,2024-10-14,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,36415,COLLECTION VENOUS BLOOD VENIPUNCTURE,Z00.00,Encounter for general adult medical examinatio...,1.508949e+09,Internal Medicine,LAB,"Southside Internal Medicine, PC",SC,PRIVATE
3963698,2024-11-19,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,73130,RADEX HAND MINIMUM 3 VIEWS,M79.641,Pain in right hand,1.891135e+09,Orthopaedic Surgery,RADIOLOGY,"Southside Internal Medicine, PC",SC,PRIVATE
3983101,2024-11-19,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,99214,OFFICE/OUTPATIENT ESTABLISHED MOD MDM 30 MIN,M79.641,Pain in right hand,1.891135e+09,Orthopaedic Surgery,SPECIALIST VISITS,"Southside Internal Medicine, PC",SC,PRIVATE
4304135,2024-07-17,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,99204,OFFICE/OUTPATIENT NEW MODERATE MDM 45 MINUTES,R19.5,Other fecal abnormalities,NaN,No Specialty,SPECIALIST VISITS,"Southside Internal Medicine, PC",SC,PRIVATE
4567425,2024-12-30,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,99212,OFFICE/OUTPATIENT ESTABLISHED SF MDM 10 MIN,M65.321,"Trigger finger, right index finger",1.558901e+09,Nurse Practitioner,PCP VISITS,"Southside Internal Medicine, PC",SC,PRIVATE
4892799,2024-09-20,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,99214,OFFICE/OUTPATIENT ESTABLISHED MOD MDM 30 MIN,M54.14,"Radiculopathy, thoracic region",NaN,No Specialty,SPECIALIST VISITS,"Southside Internal Medicine, PC",SC,PRIVATE
5087557,2024-10-14,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,G0439,"Annual wellness visit, includes a personalized...",Z00.00,Encounter for general adult medical examinatio...,1.508949e+09,Internal Medicine,PCP VISITS,"Southside Internal Medicine, PC",SC,PRIVATE
5095007,2024-10-15,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,64479,NJX AA&/STRD TFRML EPI CERVICAL/THORACIC 1 LEVEL,M54.14,"Radiculopathy, thoracic region",NaN,No Specialty,OP PROCEDURES,"Southside Internal Medicine, PC",SC,PRIVATE
5460715,2024-11-08,0000672cf36fc1586ff74101e9ee3d6e,Emory Humana MAdv,GRIFFIN,GA,30223,1508948563,"OKORO, CASIMIR",EHN,EHN Independent,...,99213,OFFICE/OUTPATIENT ESTABLISHED LOW MDM 20 MIN,M54.14,"Radiculopathy, thoracic region",1.134740e+09,Nurse Practitioner,PCP VISITS,"Southside Internal Medicine, PC",SC,PRIVATE

In [18]:
df_op['icddescription'].unique()

array(['Acute upper respiratory infection, unspecified',
       'End stage renal disease', 'Cough, unspecified', ...,
       'Other osteoporosis with current pathological fracture, left femur, subsequent encounter for fracture with routine healing',
       'Other mechanical complication of cardiac pulse generator (battery), initial encounter',
       'Derangement of anterior horn of medial meniscus due to old tear or injury, right knee'],
      dtype=object)